import type { MemeTemplate } from "@/types/template"

// Safe bottom Y formula: y_max = 1.0 - (lines * fontSize/500 * lineHeight) - 0.04 margin
// classic-impact bottom: 1.0 - (2*52/500*1.1) - 0.04 = 0.69 → use 0.68
// caption-below: bottomBarFraction=0.22, text at (1 - 0.22 + 0.02) = 0.80 with bar holding it
// expanding-brain label4: 1.0 - (2*24/500*1.2) - 0.04 = 0.845 → use 0.75 (4 blocks need spread)

export const TEMPLATES: Record<string, MemeTemplate> = {
  "classic-impact": {
    id: "classic-impact",
    name: "Classic Impact",
    description: "The OG — white Impact text top and bottom",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "top",
        role: "top",
        defaultText: "TOP TEXT",
        x: 0.05, y: 0.03, width: 0.9,
        align: "center",
        fontFamily: "Impact",
        fontSize: 52,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 2,
        shadowEnabled: false,
        shadowColor: "#000000",
        shadowBlur: 0,
        draggable: true,
        upperCase: true,
        padding: 4,
        lineHeight: 1.1,
      },
      {
        id: "bottom",
        role: "bottom",
        // y=0.68: at 480px → 326px. 2 lines of Impact52: 2*(52/500*480)*1.1=109px → 435px < 480 ✓
        defaultText: "BOTTOM TEXT",
        x: 0.05, y: 0.68, width: 0.9,
        align: "center",
        fontFamily: "Impact",
        fontSize: 52,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 2,
        shadowEnabled: false,
        shadowColor: "#000000",
        shadowBlur: 0,
        draggable: true,
        upperCase: true,
        padding: 4,
        lineHeight: 1.1,
      },
    ],
  },

  "caption-below": {
    id: "caption-below",
    name: "Caption Below",
    description: "Photo on top, clean caption bar below — Instagram style",
    aspectRatio: 1,
    imageObjectFit: "cover",
    // bottomBarFraction=0.22 → bottom 22% is caption bar, always scales with canvas
    bottomBarFraction: 0.22,
    bottomBarColor: "#FFFFFF",
    textBlocks: [
      {
        id: "caption",
        role: "bottom",
        defaultText: "when you finally fix the bug at 2am",
        // y=0.80 → sits inside the caption bar (bar starts at 1-0.22=0.78)
        x: 0.04, y: 0.80, width: 0.92,
        align: "center",
        fontFamily: "Arial",
        fontSize: 30,
        fill: "#111111",
        stroke: "",
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: "#000000",
        shadowBlur: 0,
        draggable: true,
        upperCase: false,
        padding: 6,
        lineHeight: 1.3,
      },
    ],
  },

  "this-is-fine": {
    id: "this-is-fine",
    name: "This Is Fine",
    description: "Centered text, warm overlay — existential dread vibes",
    aspectRatio: 1,
    imageObjectFit: "cover",
    overlayColor: "#FF6B35",
    overlayOpacity: 0.25,
    textBlocks: [
      {
        id: "center",
        role: "center",
        defaultText: "This is fine.",
        // y=0.38: centered-ish. 2 lines of Georgia48: 2*(48/500*480)*1.2=110px → 372px < 480 ✓
        x: 0.08, y: 0.38, width: 0.84,
        align: "center",
        fontFamily: "Georgia",
        fontSize: 48,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 8,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
    ],
  },

  "minimal-top": {
    id: "minimal-top",
    name: "Minimal Top",
    description: "Single clean top caption — art meme aesthetic",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "top",
        role: "top",
        defaultText: "me pretending to be fine",
        x: 0.05, y: 0.04, width: 0.9,
        align: "center",
        fontFamily: "Arial",
        fontSize: 36,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
    ],
  },

  "drake-pointing": {
    id: "drake-pointing",
    name: "Drake",
    description: "Two-panel comparison — reject vs approve",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "label1",
        role: "label1",
        defaultText: "Writing clean code",
        // Top half: y=0.06, width=0.44 on right side
        x: 0.52, y: 0.06, width: 0.44,
        align: "left",
        fontFamily: "Impact",
        fontSize: 30,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 3,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label2",
        role: "label2",
        defaultText: "Copy-pasting Stack Overflow",
        // Bottom half: y=0.55. 2 lines of Impact30: 2*(30/500*480)*1.2=69px → 55%*480+69=333px < 480 ✓
        x: 0.52, y: 0.55, width: 0.44,
        align: "left",
        fontFamily: "Impact",
        fontSize: 30,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 3,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
    ],
  },

  "distracted-boyfriend": {
    id: "distracted-boyfriend",
    name: "Distracted",
    description: "Three-label overlay — left, right, far-left",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "label1",
        role: "label1",
        defaultText: "Me",
        x: 0.34, y: 0.05, width: 0.24,
        align: "center",
        fontFamily: "Impact",
        fontSize: 30,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 3,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label2",
        role: "label2",
        defaultText: "New JS framework",
        x: 0.60, y: 0.05, width: 0.36,
        align: "center",
        fontFamily: "Impact",
        fontSize: 30,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 3,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label3",
        role: "label3",
        defaultText: "My actual deadline",
        // Bottom left area, safe: y=0.62. 2 lines of Impact30: 69px → 62%*480+69=367px < 480 ✓
        x: 0.04, y: 0.62, width: 0.28,
        align: "center",
        fontFamily: "Impact",
        fontSize: 30,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 3,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
    ],
  },

  "expanding-brain": {
    id: "expanding-brain",
    name: "Galaxy Brain",
    description: "Four escalating text positions — increasingly enlightened",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "label1",
        role: "label1",
        defaultText: "Using tabs",
        // Quadrant 1: top-left area y=0.04
        x: 0.05, y: 0.04, width: 0.9,
        align: "center",
        fontFamily: "Arial",
        fontSize: 28,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label2",
        role: "label2",
        defaultText: "Using spaces",
        // Quadrant 2: y=0.28
        x: 0.05, y: 0.28, width: 0.9,
        align: "center",
        fontFamily: "Arial",
        fontSize: 28,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label3",
        role: "label3",
        defaultText: "Mixing both",
        // Quadrant 3: y=0.52
        x: 0.05, y: 0.52, width: 0.9,
        align: "center",
        fontFamily: "Arial",
        fontSize: 28,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
      {
        id: "label4",
        role: "label4",
        defaultText: "No indentation at all",
        // Quadrant 4: y=0.72. 2 lines of Arial28: 2*(28/500*480)*1.2=64px → 72%*480+64=410px < 480 ✓
        x: 0.05, y: 0.72, width: 0.9,
        align: "center",
        fontFamily: "Arial",
        fontSize: 28,
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: false,
        padding: 4,
        lineHeight: 1.2,
      },
    ],
  },

  "chaos-mode": {
    id: "chaos-mode",
    name: "Chaos Mode",
    description: "Scattered text, mixed vibes — unhinged energy",
    aspectRatio: 1,
    imageObjectFit: "cover",
    textBlocks: [
      {
        id: "top",
        role: "top",
        defaultText: "CHAOS",
        // Top-left, short word — unlikely to overflow
        x: 0.03, y: 0.03, width: 0.65,
        align: "left",
        fontFamily: "Impact",
        fontSize: 56,
        fill: "#FF0040",
        stroke: "#FFFFFF",
        strokeWidth: 2,
        shadowEnabled: true,
        shadowColor: "#FF0040",
        shadowBlur: 10,
        draggable: true,
        upperCase: true,
        padding: 2,
        lineHeight: 1.0,
      },
      {
        id: "bottom",
        role: "bottom",
        defaultText: "WE LOVE TO SEE IT",
        // y=0.70: 2 lines of Arial30: 2*(30/500*480)*1.1=63px → 70%*480+63=399px < 480 ✓
        x: 0.08, y: 0.70, width: 0.84,
        align: "center",
        fontFamily: "Arial",
        fontSize: 30,
        fill: "#FFFF00",
        stroke: "#000000",
        strokeWidth: 1.5,
        shadowEnabled: true,
        shadowColor: "#000000",
        shadowBlur: 4,
        draggable: true,
        upperCase: true,
        padding: 4,
        lineHeight: 1.1,
      },
    ],
  },
}

export const TEMPLATE_LIST = Object.values(TEMPLATES)
